apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: unexist
  labels:
    strimzi.io/cluster: todo-kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: todo-titles
          patternType: literal
        operation: All
        host: '*'
      - resource:
          type: topic
          name: todo-descriptions
          patternType: literal
        operation: All
        host: '*'