apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: postgres
spec:
  databases: # Databasename: Databaseowner
    todos: unexist
  numberOfInstances: 2
  postgresql:
    version: '11'
  teamId: unexist
  users:
    todos: [] # User without special roles
    unexist: # User with special roles
      - superuser
      - createdb
  volume:
    size: 2Gi
