version: "3.5"

services:
  # Install zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    environment:
      SERVICE_NAME: zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  # Install kafka and create needed topics
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    hostname: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  # Install schema registry
  schema-registry:
    container_name: registry
    image: apicurio/apicurio-registry-mem:1.2.2.Final
    ports:
      - 8081:8080
    environment:
      QUARKUS_PROFILE: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APPLICATION_ID: registry_id
      APPLICATION_SERVER: localhost:9000
    depends_on:
      - kafka

  # Create topics
  create-topics:
    container_name: create-topics
    image: confluentinc/cp-kafka
    command: bash -c "kafka-topics --bootstrap-server kafka:9092 --create --topic todo_created --partitions 1 --replication-factor 1 --if-not-exists"
    depends_on:
      - kafka

